/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    // ==========================================
    // בדיקות עבור הפונקציה reverse
    // ==========================================

    @Test
    void testReverseNormalString() {
        String result = App.reverse("hello");
        assertEquals("olleh", result, "The string 'hello' should be reversed to 'olleh'");
    }

    @Test
    void testReverseEmptyString() {
        String result = App.reverse("");
        assertEquals("", result, "An empty string should return an empty string");
        assertTrue(result.isEmpty(), "Result should be empty");
    }

    @Test
    void testReverseSingleCharacterString() {
        String result = App.reverse("a");
        assertEquals("a", result, "A single character string should remain the same");
        assertEquals(1, result.length(), "Length should remain 1");
    }

    // ==========================================
    // בדיקות עבור הפונקציה isPalindrome
    // ==========================================

    @Test
    void testIsPalindromeNormalPositive() {
        assertTrue(App.isPalindrome("racecar"), "'racecar' should be recognized as a palindrome");
    }

    @Test
    void testIsPalindromeNormalNegative() {
        assertFalse(App.isPalindrome("hello"), "'hello' is not a palindrome");
    }

    @Test
    void testIsPalindromeWithSpacesAndCaps() {
        assertTrue(App.isPalindrome("A man a plan a canal Panama"),
                "The function should clear spaces and ignore case to find it is a palindrome");
    }

    // ==========================================
    // בדיקות עבור הפונקציה isAnagram
    // ==========================================

    @Test
    void testIsAnagramPositive() {
        assertTrue(App.isAnagram("listen", "silent"), "Valid lowercase anagrams should return true");
    }

    @Test
    void testIsAnagramNegative() {
        assertFalse(App.isAnagram("hello", "world"), "Completely different words should return false");
    }

    @Test
    void testIsAnagramWithSpacesAndCase() {
        assertTrue(App.isAnagram("Dormitory", "Dirty room"),
                "Anagrams with mixed case and spaces should return true as they should be ignored");
    }

    // ==========================================
    // בדיקות עבור הפונקציה filterEvens
    // ==========================================

    @Test
    void testFilterEvensNormalList() {
        List<Integer> input = List.of(1, 2, 3, 4, 5);
        List<Integer> expected = List.of(2, 4);
        assertEquals(expected, App.filterEvens(input), "Should filter and return only even numbers");
    }

    @Test
    void testFilterEvensAllEvens() {
        List<Integer> input = List.of(2, 4, 6, 8);
        List<Integer> expected = List.of(2, 4, 6, 8);
        assertEquals(expected, App.filterEvens(input), "Should return the same list when all numbers are even");
    }

    @Test
    void testFilterEvensAllOdds() {
        List<Integer> input = List.of(1, 3, 5, 7);
        List<Integer> result = App.filterEvens(input);
        assertTrue(result.isEmpty(), "Should return an empty list when all numbers are odd");
    }

    @Test
    void testFilterEvensEmptyList() {
        List<Integer> input = List.of();
        List<Integer> result = App.filterEvens(input);
        assertTrue(result.isEmpty(), "Should return an empty list when the input list is empty");
    }

    // ==========================================
    // בדיקות עבור הפונקציות המתמטיות
    // ==========================================

    @Test
    void testAdd_Normative() {
        assertEquals(9, App.add(5, 4), "5+4 should equal 9");
    }

    @Test
    void testAdd_EdgeCases() {
        assertEquals(3, App.add(5, -2), "5+(-2) should equal 3");
        assertEquals(0, App.add(0, 0), "0+0 should equal 0");
        assertEquals(7, App.add(7, 0), "7+0 should equal 7");
    }

    @Test
    void testIsPrime() {
        assertTrue(App.isPrime(7), "7 is a prime number");
        assertFalse(App.isPrime(4), "4 is not a prime number");
        assertFalse(App.isPrime(1), "1 is not prime");
        assertFalse(App.isPrime(0), "0 is not prime");
        assertFalse(App.isPrime(-5), "Negative numbers are not prime");
    }

    @Test
    void testFactorial() {
        assertEquals(120, App.factorial(5), "Factorial of 5 should be 120");
        assertEquals(1, App.factorial(0), "Factorial of 0 should be 1");
        assertThrows(IllegalArgumentException.class, () -> {
            App.factorial(-1);
        }, "Factorial of a negative number should throw IllegalArgumentException");
    }

    @Test
    void testAverage() {
        assertEquals(2.0, App.average(new int[]{1, 2, 3}), 0.001, "Average of {1, 2, 3} should be 2.0");
        assertEquals(2.5, App.average(new int[]{2, 3}), 0.001, "Average of {2, 3} should be 2.5");
        assertThrows(IllegalArgumentException.class, () -> {
            App.average(new int[]{});
        }, "Calculating average of an empty array should throw IllegalArgumentException");
    }

// ==========================================
    // בדיקות עבור הפונקציה fibonacciUpTo
    // ==========================================

    @Test
    void testFibonacciUpToNormalLimit() {
        // Arrange
        List<Integer> expected = List.of(0, 1, 1, 2, 3, 5, 8);
        
        // Act
        List<Integer> result = App.fibonacciUpTo(10);
        
        // Assert
        assertEquals(expected, result, "Should return Fibonacci sequence up to 10");
        assertFalse(result.isEmpty(), "The result list should not be empty");
    }

    @Test
    void testFibonacciUpToZero() {
        // Arrange
        List<Integer> expected = List.of(0);
        
        // Act
        List<Integer> result = App.fibonacciUpTo(0);
        
        // Assert
        assertEquals(expected, result, "Should return only [0] when the limit is 0");
        assertEquals(1, result.size(), "The size of the list should be exactly 1");
    }

    @Test
    void testFibonacciUpToOne() {
        // Arrange
        List<Integer> expected = List.of(0, 1, 1);
        
        // Act
        List<Integer> result = App.fibonacciUpTo(1);
        
        // Assert
        assertEquals(expected, result, "Should return [0, 1, 1] when the limit is 1");
    }

    @Test
    void testFibonacciUpToNegative() {
        // Arrange & Act & Assert combined for Exceptions
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            App.fibonacciUpTo(-5);
        }, "Should throw IllegalArgumentException for negative input");
        
        // Additional Assert to verify the exception message
        assertEquals("Negative input", exception.getMessage(), "Exception message should match exactly");
    }


    // ==========================================
    // בדיקות עבור הפונקציה charFrequency
    // ==========================================

    @Test
    void testCharFrequencyNormalString() {
        // Arrange
        String input = "hello";
        Map<Character, Integer> expected = Map.of('h', 1, 'e', 1, 'l', 2, 'o', 1);

        // Act
        Map<Character, Integer> result = App.charFrequency(input);

        // Assert
        assertEquals(expected, result, "Should return a map with correct character frequencies for 'hello'");
        assertEquals(2, result.get('l'), "Frequency of 'l' should be exactly 2");
    }

    @Test
    void testCharFrequencyEmptyString() {
        // Arrange
        String input = "";

        // Act
        Map<Character, Integer> result = App.charFrequency(input);

        // Assert
        assertTrue(result.isEmpty(), "The returned map should be completely empty for an empty string");
        assertEquals(0, result.size(), "The size of the map should be 0");
    }

    @Test
    void testCharFrequencyCaseSensitivityAndSpaces() {
        // Arrange
        String input = "A a!";
        Map<Character, Integer> expected = Map.of('A', 1, ' ', 1, 'a', 1, '!', 1);

        // Act
        Map<Character, Integer> result = App.charFrequency(input);

        // Assert
        assertEquals(expected, result, "Should treat uppercase, lowercase, spaces, and special characters differently");
        assertTrue(result.containsKey(' '), "The map must contain a space character as a valid key");
        assertEquals(4, result.size(), "The map should contain exactly 4 unique character keys");
    }


    // ==========================================
    // בדיקות עבור הפונקציה mostCommonWord
    // ==========================================

    @Test
    void testMostCommonWordNormalText() {
        // Arrange
        String text = "apple banana apple orange apple banana";
        
        // Act
        String result = App.mostCommonWord(text);
        
        // Assert
        assertEquals("apple", result, "The most common word should be 'apple'");
        assertNotEquals("banana", result, "Should not return the second most common word");
    }

    @Test
    void testMostCommonWordMixedCaseAndPunctuation() {
        // Arrange
        String text = "Hello world! hello, HELLO... world.";
        
        // Act
        String result = App.mostCommonWord(text);
        
        // Assert
        assertEquals("hello", result, "Should ignore case and punctuation, returning 'hello'");
        assertTrue(result.equals(result.toLowerCase()), "The returned word must be entirely in lowercase");
    }

    @Test
    void testMostCommonWordOnlyPunctuationException() {
        // Arrange
        String text = "!@# $%^ &*()";
        
        // Act & Assert
        assertThrows(NoSuchElementException.class, () -> {
            App.mostCommonWord(text);
        }, "Should throw NoSuchElementException when the text contains no valid words");
    }

    @Test
    void testMostCommonWordEmptyString() {
        // Arrange
        String text = "";
        
        // Act
        String result = App.mostCommonWord(text);
        
        // Assert
        assertEquals("", result, "An empty string returns an empty string as the split array contains one empty element");
    }

}